# $FreeBSD$

PORTNAME=	libfsl
PORTVERSION=	1.0
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	Libraries used by fossil scm

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libsqlite3.so:databases/sqlite3

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	libfsl

CFLAGS+=	-Wall

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

.include <bsd.port.mk>
